version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_DATABASE: collaboration_network
      MY_SQL_PASSWORD: example
    volumes:
      - ./myapp_dump.sql:/docker-entrypoint-initdb.d/myapp_dump.sql:ro
    ports:
      - "3306:3306"

  app:
    build:
      context: .
      dockerfile: Dockerfile.app
    depends_on:
      - db
    volumes:
      - ./:/app
    ports:
      - "8000:8000"
      - "3000:3000"
    environment:
      DATABASE_HOST: db
      DATABASE_USER: root
      DATABASE_PASSWORD: example
      DATABASE_NAME: collaboration_network
    command: >
      bash -c "
      pip install --no-cache-dir -r requirements.txt &&
      cd  node_server &&
      npm install &&
      npm install express cors body-parser nodemon &&
      node server.js 
      "

  frontend:
    build:
      context: .
      dockerfile: Dockerfile.frontend
    volumes:
      - ./front_end:/frontend
    ports:
      - "5173:5173"
    depends_on:
      - app
